FROM ballerina/ballerina:2201.10.0 AS build
WORKDIR /app
COPY . .
USER root
RUN bal build

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/bin/admin_service.jar app.jar
COPY Config.toml .
EXPOSE 8086
CMD ["java", "-jar", "app.jar"]